// 常量
export default {
  'FILE_IS_DIR': 0,
  'FILE_IS_NOT_DIR': 1,
  'FILE_TYPE_OF_DIR': 0,
  'FILE_TYPE_OF_TXT': 1,
  'FILE_TYPE_OF_WORD': 11,
  'FILE_TYPE_OF_EXCEL': 12,
  'FILE_TYPE_OF_POWERPOINT': 13,
  'FILE_TYPE_OF_PDF': 14,
  'FILE_TYPE_OF_PIC': 2,
  'FILE_TYPE_OF_MUSIC': 3,
  'FILE_TYPE_OF_VIDEO': 4,
  'FILE_TYPE_OF_ZIP': 5,
  'FILE_TYPE_OF_APK': 6,
  'FILE_TYPE_OF_OTHER': 9,
  'USER_STATUS_NORMAL': 0,
  'USER_STATUS_VIP': 2
}
